### ISSUE TITLE
Error ocurred during app execution. Attaching log 

### ISSUE THREAD

**Issue by MatiasArregin** [rayofhope-dev/dialog-editor#26]
This is the log when I try to open the app. I used to be able to open it but now I cant and I don't know what im doing wrong.
Sometimes i manually edit my dialog file but i never had problems with that. 

Thank you for your time :)

![image](https://github.com/user-attachments/assets/d6a26b5d-54a5-40b2-b623-e695fb060e9b)

Error message: La invocación del constructor del tipo 'xrSDK.Editor.DialogEditor.Windows.MainPage' que coincide con las restricciones de enlace especificadas produjo una excepción.
Stack trace: 
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

========================================================

Error message: An XML comment cannot contain '--', and '-' cannot be the last character. Line 18, position 4.
Stack trace: 
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseCDataOrComment(XmlNodeType type, Int32& outStartPos, Int32& outEndPos)
   at System.Xml.XmlTextReaderImpl.ParseCDataOrComment(XmlNodeType type)
   at System.Xml.XmlTextReaderImpl.ParseComment()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri)
   at xrSDK.Editor.DialogEditor.Helpers.LocalizationFileHelper.Load(String path, List`1 localizations, LocaleSettings localeSettings)
   at xrSDK.Editor.DialogEditor.Helpers.FileHelper.LoadLocalization()
   at xrSDK.Editor.DialogEditor.Windows.MainPage.LoadDialogs()
   at xrSDK.Editor.DialogEditor.Controls.Menu.TriggerRootDirectoryChanged()
   at xrSDK.Editor.DialogEditor.Windows.MainPage..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)

**Comment by MatiasArregin** [comment]
I already have it working. Issue was that I added some --commentary in dialog_ files and st_dialogs. Ive deleted only comments in dialog_ files but not in st_dialogs xd.
By deleting all comments, tool is working correctly.
